---
- hosts: "servers"
  become: yes
  remote_user: test
  become_user: root
  tasks:

  - name: Install curl
    apt:
      name: curl
      state: latest

  - name: This is the Debian package repository
    shell: 'curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee \
    /usr/share/keyrings/jenkins-keyring.asc > /dev/null'

  - name: Then add a Jenkins apt repository entry
    shell: 'echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
    https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
    /etc/apt/sources.list.d/jenkins.list > /dev/null'

  - name: Update
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Upgrade
    apt: upgrade=dist force_apt_get=yes

  - name: Install java
    apt:
      name: openjdk-11-jre
      state: present

  - name: Install jenkins
    apt:
      name: jenkins
      state: latest
      update_cache: yes

  - name: daemon-reload to pick up config changes
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Start jenkins
    ansible.builtin.systemd:
      name: jenkins
      state: started
